version: '3.4'

networks:
  dapr-net:
  
services:
  myfrontend:
    image: ${DOCKER_REGISTRY-}myfrontend
    build:
      context: .
      dockerfile: MyFrontEnd/Dockerfile
    depends_on:
      - dapr-placement
      - redis
      - zipkin
      - mybackend 
    networks: 
      - dapr-net
    environment:
      - ZIPKIN_BASE_URL=http://zipkin:9411/api/v2/spans

  myfrontend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
        "-app-id", "MyFrontEnd", 
        "-app-port", "80",
        "-dapr-http-port", "3500",
        "-log-level", "debug",
        "-enable-api-logging", "true",
        "-placement-host-address", "dapr-placement:50000",
        "-dapr-tracing" ]
    depends_on:
      - myfrontend
    network_mode: "service:myfrontend"
    environment:
      - ZIPKIN_ADDRESS=zipkin:9411

  mybackend:
    image: ${DOCKER_REGISTRY-}mybackend
    build:
      context: .
      dockerfile: MyBackEnd/Dockerfile
    depends_on:
      - dapr-placement
      - redis
      - zipkin
    networks: 
      - dapr-net
    environment:
      - ZIPKIN_BASE_URL=http://zipkin:9411/api/v2/spans

  mybackend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
        "-app-id", "MyBackEnd", 
        "-app-port", "80",
        "-dapr-http-port", "3500",
        "-log-level", "debug",
        "-enable-api-logging", "true",
        "-placement-host-address", "dapr-placement:50000",
        "-dapr-tracing",
        "-dapr-tracing-exporter", "zipkin" ]
    depends_on:
      - mybackend
    network_mode: "service:mybackend"
    environment:
      - ZIPKIN_ADDRESS=zipkin:9411

  envoygateway:
    build: Envoy/
    networks:
      - dapr-net
    ports:
      - "9902:9902"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  envoygateway-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
      "-app-id", "EnvoyGateway", 
      "-app-port", "10000",
      "-dapr-http-port", "3500",
      "-log-level", "info",
      "-enable-api-logging", "true",
      "-placement-host-address", "dapr-placement:50000",
      "-dapr-tracing" ]
    depends_on:
      - envoygateway
    network_mode: "service:envoygateway"
    environment:
      - ZIPKIN_ADDRESS=zipkin:9411

  nginx:
    container_name: nginx
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context: .
      dockerfile: Nginx/Dockerfile
    ports:
      - "8090:80"
    networks:
      - dapr-net
    depends_on:
      - myfrontend
    volumes:
      - "./Nginx/nginx.conf:/etc/nginx/nginx.conf"

  zipkin:
    image: openzipkin/zipkin-slim:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - dapr-net

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"
    networks:
      - dapr-net

  dapr-placement:
    image: "daprio/dapr:latest"
    command: [ "./placement", 
        "--port", "50000", 
        "--log-level", "debug" ]
    ports:
      - "50000:50000"
    networks:
      - dapr-net
